# test_tag.tavern.yaml
---

test_name: Test Tag Microservices

stages:
        - name: Add an article with a new tag
          request:
                url: http://127.0.0.1:5000/tag/addtag
                method: POST
          response:
                  status_code: 404

---

test_name: Test Tag Microservices

stages:
        - name: List all articles with a new tag
          request:
                url: http://127.0.0.1:5000/tag/gettag
                method: POST
          response:
                  status_code: 404

---

test_name: Test Tag Microservices

stages:
        - name: Add another tag to the article
          request:
                url: http://127.0.0.1:5000/tag/addtag
                method: POST
          response:
                  status_code: 404

---

test_name: Test Tag Microservices

stages:
        - name: Delete one of the tags from the article
          request:
                url: http://127.0.0.1:5000/tag/deletetag
                json:
                        articleId: 1
                method: DELETE
          response:
                  status_code: 404

---

test_name: Test Tag Microservices

stages:
        - name: Add a tag to an article that doesn't exist
          request:
                url: http://127.0.0.1:5000/tag/addtag
                json:
                        username: enrrique
                        password: test
                method: POST
                headers:
                        content-type: application/json
          response:
                  status_code: 404


Collapse




Message Input


Joshua Ungheanu
