# test_users.tavern.yaml
---

test_name: Try to change the password for a user that does not exist

stages:
  - name: Passwords of users in the database should only be allowed to change
    request:
      url: http://127.0.0.1:5000/updatePassword
      auth:
        - zzz@gmail.com
        - zzz
      json:
        new_password: zzz
      method: PATCH
      headers:
        content-type: application/json
    response:
      status_code: 401

---

test_name: Create a user

stages:
  - name: As email is primary key, it should be made sure that it is unique
    request:
      url: http://127.0.0.1:5000/addUser
      json:
        name: kkk
        email: kkk@gmail.com
        password: kkk
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 201

---

test_name: Test for user email repeat

stages:
  - name: As email is primary key, it should be made sure that it is unique
    request:
      url: http://127.0.0.1:5000/addUser
      json:
        name: dadad
        email: kkk@gmail.com
        password: sada
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 409

---

test_name: Change the user’s password

stages:
  - name: The password shouldbe changed sucessfully and has to be hashed in database
    request:
      url: http://127.0.0.1:5000/updatePassword
      auth:
        - kkk@gmail.com
        - kkk
      json:
        newPassword: kk
      method: PATCH
      headers:
        content-type: application/json
    response:
      status_code: 200

---

test_name: Delete the user

stages:
  - name: The user profile that has to be deleted should in database

    request:
      url: http://127.0.0.1:5000/deleteUser
      auth:
        - kkk@gmail.com
        - kk
      method: DELETE
      headers:
        content-type: application/json
    response:
      status_code: 200

---

test_name: Try to change the password for the deleted user

stages:
  - name: Make sure that the deleted user's password cannot be updated/changed
    request:
        url: http://127.0.0.1:5000/deleteUser
        auth:
          - kkk@gmail.com
          - kk
        method: DELETE
        headers:
          content-type: application/json
    response:
      status_code: 401

Collapse




Message Input


Message Shamant
