# test_comments.tavern.yaml
---

test_name: Test Comments Microservices

stages:
        - name: Try to add a comment to an article that doesn't exist
          request:
                url: http://127.0.0.1:5000/articles/5/addcomment
                method: POST
          response:
                  status_code: 404

---

test_name: Test Comments Microservices


stages:
        - name: Post an anonymous comment on an article
          request:
                url: http://127.0.0.1:5000/articles/1/addcomment
                method: POST
          response:
                  status_code: 404

---

test_name: Test Comments Microservices


stages:
        - name: Post an authenticated comment on an article
          request:
                url: http://127.0.0.1:5000/articles/1/addcomment
                method: POST
          response:
                  status_code: 404

---

test_name: Test Comments Microservices


stages:
        - name: Check that the comments on the article were returnd in order
          request:
                 url: http://127.0.0.1:5000/articles/1/comments/recentcomments?recent=1
                method: POST
          response:
                  status_code: 404


Collapse




Message Input


Joshua Ungheanu
